apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert
spec:
  keystores:
    jks:
      passwordSecretRef:
        name: jks-password-secret
        key: password
  issuerRef:
    name: badgereader-clusterissuer
    group: cert-manager.io
    kind: ClusterIssuer
  privateKey:
    algorithm: ECDSA
    size: 256
  dnsNames:
    - badgereader-helm.badgereder.svc.cluster.local
  secretName: badgereader-cert
  commonName: badgereader
  duration: 1h
  renewBefore: 5m
