apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
    pv.kubernetes.io/provisioned-by: kubernetes.io/azure-disk
    volumehelper.VolumeDynamicallyCreatedByKey: azure-disk-dynamic-provisioner
  labels:
    failure-domain.beta.kubernetes.io/region: northeurope
  name: badgereder-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azure-disk
  azureDisk:
    cachingMode: ReadOnly
    diskName: kubernetes-dynamic-pvc-55cc9d4a-84ac-4464-9259-8f5317b75245
    diskURI: /subscriptions/21b61287-b2bd-4767-b872-b4d447d90553/resourceGroups/rancher-rnd-vinaymakam/providers/Microsoft.Compute/disks/kubernetes-dynamic-pvc-55cc9d4a-84ac-4464-9259-8f5317b75245
    fsType: ""
    kind: Managed
    readOnly: false
